### ISSUE TITLE
A 05

### ISSUE THREAD

**Issue by TawsTm** [sleepykira/GiS-SoSe-2020#1]
1. Preis als String?

2. Beide Interfaces sind identisch, mann könnte sie also zusammenfassen.

3. Du kannst neu definierte HTML-Elemente auch direkt mit ihrer Variable aufrufen. Dazu musst du nicht erst eine Id definieren und diese dann wieder suchen.

4. Die Schleifen sind eigentlich auch bis auf ein/zwei Kleinigkeiten gleich, lassen sich also auch noch zusammenfassen.

**Comment by sleepykira** [comment]
Alles klar, vielen Dank. Ich habe Preis als String gewählt, da nicht alle Artikel eine konsequente Zahl als Preis haben. Daher war ich mir unsicher wie genau ich das lösen soll, und habe Preis der Einfachheit halber nicht als Number deklariert.
